name:                set-theory
version:             0.1.0.0
github:              "lyncmi07/SetTheory"
license:             LGPL-3
author:              "Michael Lynch"
maintainer:          "lyncmi07@yahoo.co.uk"
copyright:           "Copyright (c) 2019 Michael Lynch"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simple library for providing set theory to haskell datatypes
category:            Mathematics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lyncmi07/SetTheory#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers

tests:
  set-theory-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - set-theory
